
package clientews.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraPercursoImpl", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraPercursoImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculaValorTotalDoPercurso", targetNamespace = "http://ws/", className = "ws.CalculaValorTotalDoPercurso")
    @ResponseWrapper(localName = "calculaValorTotalDoPercursoResponse", targetNamespace = "http://ws/", className = "ws.CalculaValorTotalDoPercursoResponse")
    @Action(input = "http://ws/CalculadoraPercursoImpl/calculaValorTotalDoPercursoRequest", output = "http://ws/CalculadoraPercursoImpl/calculaValorTotalDoPercursoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws/CalculadoraPercursoImpl/calculaValorTotalDoPercurso/Fault/Exception")
    })
    public double calculaValorTotalDoPercurso(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws Exception_Exception
    ;

}
